<a href="https://colab.research.google.com/github/RoihansLab/Data-Mining-Project/blob/main/Volcano_eruption.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**1. PROBLEM**
What if scientists could anticipate volcanic eruptions as they predict the weather? While determining rain or shine days in advance is more difficult, weather reports become more accurate on shorter time scales. A similar approach with volcanoes could make a big impact. Just one unforeseen eruption can result in tens of thousands of lives lost. If scientists could reliably predict when a volcano will next erupt, evacuations could be more timely and the damage mitigated.

Currently, scientists often identify “time to eruption” by surveying volcanic tremors from seismic signals. In some volcanoes, this intensifies as volcanoes awaken and prepare to erupt. Unfortunately, patterns of seismicity are difficult to interpret. In very active volcanoes, current approaches predict eruptions some minutes in advance, but they usually fail at longer-term predictions.

## **1. Import Library**

In [1]:
import pandas as pd
import numpy as np

## **2. Feature Selection**

### **2.1.Load Datasets**

In [2]:
df_eruption = pd.read_csv("/content/eruptions.csv")
df_event = pd.read_csv("/content/events.csv")
df_volcano = pd.read_csv("/content/volcano.csv")
df_sulfur = pd.read_csv("/content/sulfur.csv")
df_tree_rings = pd.read_csv("/content/tree_rings.csv")

### **2.2. Feature Selection**

#### **2.2.1. Eruption Datasets**

In [3]:
df_eruption.head(50)

,volcano_number,volcano_name,eruption_number,eruption_category,area_of_activity,vei,start_year,start_month,start_day,evidence_method_dating,end_year,end_month,end_day,latitude,longitude
0,266030,Soputan,22354,Confirmed Eruption,NaN,NaN,2020.0,3.0,23.0,Historical Observations,2020.0,4.0,2.0,1.112,124.737
1,343100,San Miguel,22355,Confirmed Eruption,NaN,NaN,2020.0,2.0,22.0,Historical Observations,2020.0,2.0,22.0,13.434,-88.269
2,233020,"Fournaise, Piton de la",22343,Confirmed Eruption,NaN,NaN,2020.0,2.0,10.0,Historical Observations,2020.0,4.0,6.0,-21.244,55.708
3,345020,Rincon de la Vieja,22346,Confirmed Eruption,NaN,NaN,2020.0,1.0,31.0,Historical Observations,2020.0,4.0,17.0,10.830,-85.324
4,353010,Fernandina,22347,Confirmed Eruption,NaN,NaN,2020.0,1.0,12.0,Historical Observations,2020.0,1.0,12.0,-0.370,-91.550
5,273070,Taal,22344,Confirmed Eruption,NaN,NaN,2020.0,1.0,12.0,Historical Observations,2020.0,1.0,22.0,14.002,120.993
6,282050,Kuchinoerabujima,22345,Confirmed Eruption,NaN,NaN,2020.0,1.0,11.0,Historical Observations,2020.0,4.0,17.0,30.443,130.217
7,241040,Whakaari/White Island,22338,Confirmed Eruption,1978/90 Crater Complex,2.0,2019.0,12.0,9.0,Historical Observations,2019.0,12.0,9.0,-37.520,177.180
8,311060,Semisopochnoi,22341,Confirmed Eruption,NaN,NaN,2019.0,12.0,7.0,Historical Observations,2020.0,3.0,15.0,51.930,179.580
9,284096,Nishinoshima,22340,Confirmed Eruption,NaN,1.0,2019.0,12.0,5.0,Historical Observations,2020.0,4.0,17.0,27.247,140.874
10,311240,Cleveland,22342,Uncertain Eruption,NaN,NaN,2019.0,11.0,7.0,Historical Observations,2019.0,12.0,7.0,52.825,-169.944
11,282060,Kikai,22339,Confirmed Eruption,NaN,NaN,2019.0,11.0,2.0,Historical Observations,2020.0,4.0,16.0,30.793,130.305
12,300260,Klyuchevskoy,22335,Confirmed Eruption,NaN,NaN,2019.0,10.0,24.0,Historical Observations,2020.0,4.0,17.0,56.056,160.642
13,243070,Lateiki,22334,Confirmed Eruption,NaN,1.0,2019.0,10.0,13.0,Historical Observations,2019.0,10.0,22.0,-19.180,-174.870
14,283110,Asamayama,22326,Confirmed Eruption,NaN,NaN,2019.0,8.0,7.0,Historical Observations,2019.0,8.0,25.0,36.406,138.523
15,357090,Copahue,22336,Confirmed Eruption,NaN,NaN,2019.0,8.0,2.0,Historical Observations,2019.0,11.0,12.0,-37.856,-71.183
16,263090,Tangkuban Parahu,22325,Confirmed Eruption,NaN,NaN,2019.0,7.0,26.0,Historical Observations,2019.0,9.0,17.0,-6.770,107.600
17,311360,Shishaldin,22330,Confirmed Eruption,Summit crater,NaN,2019.0,7.0,23.0,Historical Observations,2020.0,4.0,9.0,54.756,-163.970
18,351020,"Ruiz, Nevado del",22329,Confirmed Eruption,NaN,NaN,2019.0,7.0,23.0,Historical Observations,2020.0,4.0,13.0,4.892,-75.324
19,311060,Semisopochnoi,22328,Confirmed Eruption,NaN,NaN,2019.0,7.0,16.0,Historical Observations,2019.0,8.0,24.0,51.930,179.580
20,252120,Ulawun,22319,Confirmed Eruption,NaN,NaN,2019.0,6.0,26.0,Historical Observations,2019.0,10.0,5.0,-5.050,151.330
21,354020,Ubinas,22324,Confirmed Eruption,NaN,NaN,2019.0,6.0,24.0,Historical Observations,2019.0,12.0,24.0,-16.355,-70.903
22,290250,Raikoke,22321,Confirmed Eruption,NaN,NaN,2019.0,6.0,22.0,Historical Observations,2019.0,7.0,1.0,48.292,153.250
23,233020,"Fournaise, Piton de la",22318,Confirmed Eruption,NaN,NaN,2019.0,6.0,11.0,Historical Observations,2019.0,10.0,27.0,-21.244,55.708
24,311120,Great Sitkin,22322,Confirmed Eruption,NaN,NaN,2019.0,6.0,1.0,Historical Observations,2019.0,6.0,7.0,52.076,-176.130
25,290240,Sarychev Peak,22320,Confirmed Eruption,NaN,2.0,2019.0,5.0,16.0,Historical Observations,2019.0,10.0,7.0,48.092,153.200
26,341040,Colima,22323,Confirmed Eruption,NaN,NaN,2019.0,5.0,11.0,Historical Observations,2019.0,7.0,12.0,19.514,-103.620
27,282110,Asosan,22317,Confirmed Eruption,NaN,NaN,2019.0,4.0,16.0,Historical Observations,2020.0,4.0,17.0,32.884,131.104
28,300260,Klyuchevskoy,22310,Confirmed Eruption,NaN,NaN,2019.0,4.0,9.0,Historical Observations,2019.0,7.0,2.0,56.056,160.642
29,352090,Sangay,22312,Confirmed Eruption,NaN,NaN,2019.0,3.0,26.0,Historical Observations,2020.0,4.0,17.0,-2.005,-78.341
30,344020,San Cristobal,22311,Confirmed Eruption,NaN,NaN,2019.0,3.0,4.0,Historical Observations,2019.0,3.0,4.0,12.702,-87.004
31,233020,"Fournaise, Piton de la",22307,Confirmed Eruption,NaN,NaN,2019.0,2.0,18.0,Historical Observations,2019.0,3.0,10.0,-21.244,55.708
32,263310,Tengger Caldera,22306,Confirmed Eruption,Bromo,2.0,2019.0,2.0,18.0,Historical Observations,2019.0,7.0,28.0,-7.942,112.950
33,300130,Karymsky,22309,Confirmed Eruption,NaN,NaN,2019.0,2.0,16.0,Historical Observations,2019.0,9.0,24.0,54.049,159.443
34,345040,Poas,22303,Confirmed Eruption,NaN,NaN,2019.0,2.0,7.0,Historical Observations,2019.0,9.0,30.0,10.200,-84.233
35,261080,Sinabung,22316,Confirmed Eruption,NaN,NaN,2019.0,2.0,6.0,Historical Observations,2019.0,6.0,9.0,3.170,98.392
36,256010,Tinakula,22313,Confirmed Eruption,NaN,2.0,2018.0,12.0,8.0,Historical Observations,2020.0,4.0,11.0,-10.386,165.804
37,267020,Karangetang,22294,Confirmed Eruption,NaN,2.0,2018.0,11.0,25.0,Historical Observations,2020.0,4.0,17.0,2.781,125.407
38,357040,Planchon-Peteroa,22297,Confirmed Eruption,NaN,1.0,2018.0,11.0,7.0,Historical Observations,2019.0,5.0,7.0,-35.223,-70.568
39,351020,"Ruiz, Nevado del",22298,Uncertain Eruption,NaN,NaN,2018.0,10.0,26.0,Historical Observations,2018.0,10.0,26.0,4.892,-75.324
40,282050,Kuchinoerabujima,22296,Confirmed Eruption,NaN,3.0,2018.0,10.0,21.0,Historical Observations,2019.0,2.0,3.0,30.443,130.217
41,268060,Gamalama,22295,Confirmed Eruption,NaN,1.0,2018.0,10.0,4.0,Historical Observations,2018.0,10.0,6.0,0.800,127.330
42,266030,Soputan,22293,Confirmed Eruption,NaN,3.0,2018.0,10.0,2.0,Historical Observations,2018.0,12.0,16.0,1.112,124.737
43,260010,Barren Island,22292,Confirmed Eruption,NaN,1.0,2018.0,9.0,25.0,Historical Observations,2020.0,4.0,16.0,12.278,93.858
44,252120,Ulawun,22286,Confirmed Eruption,NaN,2.0,2018.0,9.0,21.0,Historical Observations,2018.0,10.0,12.0,-5.050,151.330
45,290200,Ketoi,22287,Uncertain Eruption,NaN,1.0,2018.0,9.0,21.0,Historical Observations,2018.0,9.0,21.0,47.350,152.475
46,290240,Sarychev Peak,22288,Confirmed Eruption,NaN,2.0,2018.0,9.0,8.0,Historical Observations,2018.0,10.0,15.0,48.092,153.200
47,311060,Semisopochnoi,22289,Confirmed Eruption,NaN,1.0,2018.0,9.0,8.0,Historical Observations,2018.0,10.0,31.0,51.930,179.580
48,312070,Veniaminof,22290,Confirmed Eruption,NaN,1.0,2018.0,9.0,4.0,Historical Observations,2018.0,12.0,23.0,56.170,-159.380
49,290390,Alaid,22281,Confirmed Eruption,NaN,1.0,2018.0,8.0,20.0,Historical Observations,2018.0,8.0,21.0,50.861,155.565

In [4]:
df_eruption.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11178 entries, 0 to 11177
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   volcano_number          11178 non-null  int64
 1   volcano_name            11178 non-null  object
 2   eruption_number         11178 non-null  int64
 3   eruption_category       11178 non-null  object
 4   area_of_activity        4694 non-null   object
 5   vei                     8272 non-null   float64
 6   start_year              11177 non-null  float64
 7   start_month             10985 non-null  float64
 8   start_day               10982 non-null  float64
 9   evidence_method_dating  9898 non-null   object
 10  end_year                4332 non-null   float64
 11  end_month               4329 non-null   float64
 12  end_day                 4326 non-null   float64
 13  latitude                11178 non-null  float64
 14  longitude               11178 non-null  float64
dtypes: float64(9), int64(2), object(4)
memory usage: 1.3+ MB

In [5]:
df_eruption.isnull().sum()

volcano_number               0
volcano_name                 0
eruption_number              0
eruption_category            0
area_of_activity          6484
vei                       2906
start_year                   1
start_month                193
start_day                  196
evidence_method_dating    1280
end_year                  6846
end_month                 6849
end_day                   6852
latitude                     0
longitude                    0
dtype: int64

In [6]:
kolom_inti = [
    'volcano_number',
    'volcano_name',
    'eruption_number',
    'eruption_category',
    'vei',
    'start_year'
]

df_eruption_new = df_eruption[kolom_inti].copy()
df_eruption_new.head(50)

,volcano_number,volcano_name,eruption_number,eruption_category,vei,start_year
0,266030,Soputan,22354,Confirmed Eruption,NaN,2020.0
1,343100,San Miguel,22355,Confirmed Eruption,NaN,2020.0
2,233020,"Fournaise, Piton de la",22343,Confirmed Eruption,NaN,2020.0
3,345020,Rincon de la Vieja,22346,Confirmed Eruption,NaN,2020.0
4,353010,Fernandina,22347,Confirmed Eruption,NaN,2020.0
5,273070,Taal,22344,Confirmed Eruption,NaN,2020.0
6,282050,Kuchinoerabujima,22345,Confirmed Eruption,NaN,2020.0
7,241040,Whakaari/White Island,22338,Confirmed Eruption,2.0,2019.0
8,311060,Semisopochnoi,22341,Confirmed Eruption,NaN,2019.0
9,284096,Nishinoshima,22340,Confirmed Eruption,1.0,2019.0
10,311240,Cleveland,22342,Uncertain Eruption,NaN,2019.0
11,282060,Kikai,22339,Confirmed Eruption,NaN,2019.0
12,300260,Klyuchevskoy,22335,Confirmed Eruption,NaN,2019.0
13,243070,Lateiki,22334,Confirmed Eruption,1.0,2019.0
14,283110,Asamayama,22326,Confirmed Eruption,NaN,2019.0
15,357090,Copahue,22336,Confirmed Eruption,NaN,2019.0
16,263090,Tangkuban Parahu,22325,Confirmed Eruption,NaN,2019.0
17,311360,Shishaldin,22330,Confirmed Eruption,NaN,2019.0
18,351020,"Ruiz, Nevado del",22329,Confirmed Eruption,NaN,2019.0
19,311060,Semisopochnoi,22328,Confirmed Eruption,NaN,2019.0
20,252120,Ulawun,22319,Confirmed Eruption,NaN,2019.0
21,354020,Ubinas,22324,Confirmed Eruption,NaN,2019.0
22,290250,Raikoke,22321,Confirmed Eruption,NaN,2019.0
23,233020,"Fournaise, Piton de la",22318,Confirmed Eruption,NaN,2019.0
24,311120,Great Sitkin,22322,Confirmed Eruption,NaN,2019.0
25,290240,Sarychev Peak,22320,Confirmed Eruption,2.0,2019.0
26,341040,Colima,22323,Confirmed Eruption,NaN,2019.0
27,282110,Asosan,22317,Confirmed Eruption,NaN,2019.0
28,300260,Klyuchevskoy,22310,Confirmed Eruption,NaN,2019.0
29,352090,Sangay,22312,Confirmed Eruption,NaN,2019.0
30,344020,San Cristobal,22311,Confirmed Eruption,NaN,2019.0
31,233020,"Fournaise, Piton de la",22307,Confirmed Eruption,NaN,2019.0
32,263310,Tengger Caldera,22306,Confirmed Eruption,2.0,2019.0
33,300130,Karymsky,22309,Confirmed Eruption,NaN,2019.0
34,345040,Poas,22303,Confirmed Eruption,NaN,2019.0
35,261080,Sinabung,22316,Confirmed Eruption,NaN,2019.0
36,256010,Tinakula,22313,Confirmed Eruption,2.0,2018.0
37,267020,Karangetang,22294,Confirmed Eruption,2.0,2018.0
38,357040,Planchon-Peteroa,22297,Confirmed Eruption,1.0,2018.0
39,351020,"Ruiz, Nevado del",22298,Uncertain Eruption,NaN,2018.0
40,282050,Kuchinoerabujima,22296,Confirmed Eruption,3.0,2018.0
41,268060,Gamalama,22295,Confirmed Eruption,1.0,2018.0
42,266030,Soputan,22293,Confirmed Eruption,3.0,2018.0
43,260010,Barren Island,22292,Confirmed Eruption,1.0,2018.0
44,252120,Ulawun,22286,Confirmed Eruption,2.0,2018.0
45,290200,Ketoi,22287,Uncertain Eruption,1.0,2018.0
46,290240,Sarychev Peak,22288,Confirmed Eruption,2.0,2018.0
47,311060,Semisopochnoi,22289,Confirmed Eruption,1.0,2018.0
48,312070,Veniaminof,22290,Confirmed Eruption,1.0,2018.0
49,290390,Alaid,22281,Confirmed Eruption,1.0,2018.0

In [7]:
df_eruption_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11178 entries, 0 to 11177
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   volcano_number     11178 non-null  int64
 1   volcano_name       11178 non-null  object
 2   eruption_number    11178 non-null  int64
 3   eruption_category  11178 non-null  object
 4   vei                8272 non-null   float64
 5   start_year         11177 non-null  float64
dtypes: float64(2), int64(2), object(2)
memory usage: 524.1+ KB

#### **2.2.2. Event Datasets**

In [8]:
df_event.head(50)

,volcano_number,volcano_name,eruption_number,eruption_start_year,event_number,event_type,event_remarks,event_date_year,event_date_month,event_date_day
0,210020,Chaine des Puys,10011,-4040,100001,Explosion,NaN,NaN,NaN,NaN
1,210020,Chaine des Puys,10011,-4040,100002,Scoria,NaN,NaN,NaN,NaN
2,210020,Chaine des Puys,10011,-4040,100003,Pyroclastic flow,NaN,NaN,NaN,NaN
3,210020,Chaine des Puys,10011,-4040,100004,Lava flow(s),NaN,NaN,NaN,NaN
4,210020,Chaine des Puys,10011,-4040,100005,Cinder cone formation,NaN,NaN,NaN,NaN
5,210020,Chaine des Puys,10011,-4040,100006,Pumice,NaN,NaN,NaN,NaN
6,210040,Calatrava Volcanic Field,10012,-3600,100008,Explosion,NaN,NaN,NaN,NaN
7,210040,Calatrava Volcanic Field,10012,-3600,100009,Pyroclastic flow,NaN,NaN,NaN,NaN
8,211003,Vulsini,10014,-104,100019,Flames,NaN,NaN,NaN,NaN
9,211004,Colli Albani,10015,-600,100021,Phreatic activity,Uncertain,NaN,NaN,NaN
10,211010,Campi Flegrei,10018,-8480,100025,Explosion,NaN,NaN,NaN,NaN
11,211010,Campi Flegrei,10018,-8480,100026,Pyroclastic flow,NaN,NaN,NaN,NaN
12,211010,Campi Flegrei,10018,-8480,100027,Pumice,NaN,NaN,NaN,NaN
13,211010,Campi Flegrei,10019,-7980,100030,Explosion,NaN,NaN,NaN,NaN
14,211010,Campi Flegrei,10019,-7980,100031,Ash,NaN,NaN,NaN,NaN
15,211010,Campi Flegrei,10019,-7980,100032,Lapilli,NaN,NaN,NaN,NaN
16,211010,Campi Flegrei,10019,-7980,100033,Pyroclastic flow,NaN,NaN,NaN,NaN
17,211010,Campi Flegrei,10019,-7980,100034,Pumice,NaN,NaN,NaN,NaN
18,211010,Campi Flegrei,10025,-2580,100036,Explosion,NaN,NaN,NaN,NaN
19,211010,Campi Flegrei,10025,-2580,100037,Ash,NaN,NaN,NaN,NaN
20,211010,Campi Flegrei,10025,-2580,100038,Lapilli,NaN,NaN,NaN,NaN
21,211010,Campi Flegrei,10025,-2580,100039,Pyroclastic flow,NaN,NaN,NaN,NaN
22,211010,Campi Flegrei,10026,-2500,100041,Explosion,NaN,NaN,NaN,NaN
23,211010,Campi Flegrei,10026,-2500,100042,Ash,NaN,NaN,NaN,NaN
24,211010,Campi Flegrei,10026,-2500,100043,Pyroclastic flow,NaN,NaN,NaN,NaN
25,211010,Campi Flegrei,10026,-2500,100044,Pumice,NaN,NaN,NaN,NaN
26,211010,Campi Flegrei,10027,-2440,100046,Explosion,NaN,NaN,NaN,NaN
27,211010,Campi Flegrei,10027,-2440,100047,Ash,NaN,NaN,NaN,NaN
28,211010,Campi Flegrei,10027,-2440,100048,Lapilli,NaN,NaN,NaN,NaN
29,211010,Campi Flegrei,10027,-2440,100049,Pyroclastic flow,NaN,NaN,NaN,NaN
30,211010,Campi Flegrei,10027,-2440,100050,Pumice,NaN,NaN,NaN,NaN
31,211010,Campi Flegrei,10028,-2330,100052,Explosion,NaN,NaN,NaN,NaN
32,211010,Campi Flegrei,10028,-2330,100053,Ash,NaN,NaN,NaN,NaN
33,211010,Campi Flegrei,10028,-2330,100054,Lapilli,NaN,NaN,NaN,NaN
34,211010,Campi Flegrei,10028,-2330,100055,Pyroclastic flow,NaN,NaN,NaN,NaN
35,211010,Campi Flegrei,10029,-2220,100057,Explosion,NaN,NaN,NaN,NaN
36,211010,Campi Flegrei,10029,-2220,100058,Ash,NaN,NaN,NaN,NaN
37,211010,Campi Flegrei,10029,-2220,100059,Lapilli,NaN,NaN,NaN,NaN
38,211010,Campi Flegrei,10029,-2220,100060,Pyroclastic flow,NaN,NaN,NaN,NaN
39,211010,Campi Flegrei,10029,-2220,100061,Pumice,NaN,NaN,NaN,NaN
40,263300,Semeru,10030,1915,100063,Explosion,Uncertain,NaN,NaN,NaN
41,263300,Semeru,10030,1915,100064,Lahar or mudflow,NaN,NaN,NaN,NaN
42,263300,Semeru,10031,1941,100066,Explosion,NaN,NaN,NaN,NaN
43,263300,Semeru,10031,1941,100067,Ash,NaN,NaN,NaN,NaN
44,263300,Semeru,10031,1941,100068,Bombs,NaN,NaN,NaN,NaN
45,211010,Campi Flegrei,10037,-1870,100069,Ash,NaN,NaN,NaN,NaN
46,211010,Campi Flegrei,10037,-1870,100070,Scoria,NaN,NaN,NaN,NaN
47,211010,Campi Flegrei,10037,-1870,100071,Pyroclastic flow,NaN,NaN,NaN,NaN
48,211010,Campi Flegrei,10037,-1870,100072,Lava flow(s),NaN,NaN,NaN,NaN
49,211010,Campi Flegrei,10037,-1870,100073,Lava dome formation,NaN,NaN,NaN,NaN

In [9]:
df_event.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41322 entries, 0 to 41321
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   volcano_number       41322 non-null  int64
 1   volcano_name         41322 non-null  object
 2   eruption_number      41322 non-null  int64
 3   eruption_start_year  41322 non-null  int64
 4   event_number         41322 non-null  int64
 5   event_type           41322 non-null  object
 6   event_remarks        4880 non-null   object
 7   event_date_year      10007 non-null  float64
 8   event_date_month     7132 non-null   float64
 9   event_date_day       5923 non-null   float64
dtypes: float64(3), int64(4), object(3)
memory usage: 3.2+ MB

In [10]:
df_event.isnull().sum()

volcano_number             0
volcano_name               0
eruption_number            0
eruption_start_year        0
event_number               0
event_type                 0
event_remarks          36442
event_date_year        31315
event_date_month       34190
event_date_day         35399
dtype: int64

In [11]:
kolom_inti = [
    'volcano_number',
    'volcano_name',
    'eruption_number',
    'eruption_start_year',
    'event_number',
    'event_type'
]

df_event_new = df_event[kolom_inti].copy()
df_event_new.head(50)

,volcano_number,volcano_name,eruption_number,eruption_start_year,event_number,event_type
0,210020,Chaine des Puys,10011,-4040,100001,Explosion
1,210020,Chaine des Puys,10011,-4040,100002,Scoria
2,210020,Chaine des Puys,10011,-4040,100003,Pyroclastic flow
3,210020,Chaine des Puys,10011,-4040,100004,Lava flow(s)
4,210020,Chaine des Puys,10011,-4040,100005,Cinder cone formation
5,210020,Chaine des Puys,10011,-4040,100006,Pumice
6,210040,Calatrava Volcanic Field,10012,-3600,100008,Explosion
7,210040,Calatrava Volcanic Field,10012,-3600,100009,Pyroclastic flow
8,211003,Vulsini,10014,-104,100019,Flames
9,211004,Colli Albani,10015,-600,100021,Phreatic activity
10,211010,Campi Flegrei,10018,-8480,100025,Explosion
11,211010,Campi Flegrei,10018,-8480,100026,Pyroclastic flow
12,211010,Campi Flegrei,10018,-8480,100027,Pumice
13,211010,Campi Flegrei,10019,-7980,100030,Explosion
14,211010,Campi Flegrei,10019,-7980,100031,Ash
15,211010,Campi Flegrei,10019,-7980,100032,Lapilli
16,211010,Campi Flegrei,10019,-7980,100033,Pyroclastic flow
17,211010,Campi Flegrei,10019,-7980,100034,Pumice
18,211010,Campi Flegrei,10025,-2580,100036,Explosion
19,211010,Campi Flegrei,10025,-2580,100037,Ash
20,211010,Campi Flegrei,10025,-2580,100038,Lapilli
21,211010,Campi Flegrei,10025,-2580,100039,Pyroclastic flow
22,211010,Campi Flegrei,10026,-2500,100041,Explosion
23,211010,Campi Flegrei,10026,-2500,100042,Ash
24,211010,Campi Flegrei,10026,-2500,100043,Pyroclastic flow
25,211010,Campi Flegrei,10026,-2500,100044,Pumice
26,211010,Campi Flegrei,10027,-2440,100046,Explosion
27,211010,Campi Flegrei,10027,-2440,100047,Ash
28,211010,Campi Flegrei,10027,-2440,100048,Lapilli
29,211010,Campi Flegrei,10027,-2440,100049,Pyroclastic flow
30,211010,Campi Flegrei,10027,-2440,100050,Pumice
31,211010,Campi Flegrei,10028,-2330,100052,Explosion
32,211010,Campi Flegrei,10028,-2330,100053,Ash
33,211010,Campi Flegrei,10028,-2330,100054,Lapilli
34,211010,Campi Flegrei,10028,-2330,100055,Pyroclastic flow
35,211010,Campi Flegrei,10029,-2220,100057,Explosion
36,211010,Campi Flegrei,10029,-2220,100058,Ash
37,211010,Campi Flegrei,10029,-2220,100059,Lapilli
38,211010,Campi Flegrei,10029,-2220,100060,Pyroclastic flow
39,211010,Campi Flegrei,10029,-2220,100061,Pumice
40,263300,Semeru,10030,1915,100063,Explosion
41,263300,Semeru,10030,1915,100064,Lahar or mudflow
42,263300,Semeru,10031,1941,100066,Explosion
43,263300,Semeru,10031,1941,100067,Ash
44,263300,Semeru,10031,1941,100068,Bombs
45,211010,Campi Flegrei,10037,-1870,100069,Ash
46,211010,Campi Flegrei,10037,-1870,100070,Scoria
47,211010,Campi Flegrei,10037,-1870,100071,Pyroclastic flow
48,211010,Campi Flegrei,10037,-1870,100072,Lava flow(s)
49,211010,Campi Flegrei,10037,-1870,100073,Lava dome formation

#### **2.2.3. Sulfur Datasets**

In [12]:
df_sulfur.head(50)

       year   neem      wdc
0   705.958  13.64  14.5850
1   705.875  14.40  12.8170
2   705.792  15.78  11.2710
3   705.708  17.42   9.8681
4   705.625  18.29   8.7793
5   705.542  18.36   8.5262
6   705.458  17.83   8.5077
7   705.375  16.80   9.1211
8   705.292  15.63  10.2940
9   705.208  15.07  11.8180
10  705.125  15.21  12.6780
11  705.042  16.22  13.6530
12  704.958  16.02  13.7170
13  704.875  14.23  12.8870
14  704.792  12.46  11.2840
15  704.708  11.06   9.9471
16  704.625  10.61   9.0934
17  704.542  11.19   8.0845
18  704.458  11.50   7.9594
19  704.375  11.67   8.3843
20  704.292  12.35   9.4849
21  704.208  13.62  11.1200
22  704.125  14.73  13.5140
23  704.042  14.51  15.3130
24  703.958  14.08  16.2130
25  703.875  12.93  16.2350
26  703.792  11.89  14.2910
27  703.708  11.09  11.8400
28  703.625  10.64   9.8742
29  703.542  11.06   9.0508
30  703.458  12.05   8.6457
31  703.375  13.31   7.8141
32  703.292  14.93  15.5560
33  703.208  16.15  14.6230
34  703.125  17.00  13.2580
35  703.042  17.40  11.4960
36  702.958  16.89   9.6132
37  702.875  15.35   8.6202
38  702.792  13.80   8.6325
39  702.708  13.18   9.2305
40  702.625  13.08  10.8350
41  702.542  13.17  12.8030
42  702.458  13.39  14.5910
43  702.375  13.85  16.6520
44  702.292  14.54  17.3880
45  702.208  15.11  16.3160
46  702.125  15.13  13.9090
47  702.042  14.70  10.8800
48  701.958  13.92   9.1351
49  701.875  13.15   7.9909

In [13]:
df_sulfur.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2252 entries, 0 to 2251
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   year    1962 non-null   float64
 1   neem    1962 non-null   float64
 2   wdc     2252 non-null   float64
dtypes: float64(3)
memory usage: 52.9 KB

In [14]:
df_sulfur.isnull().sum()

year    290
neem    290
wdc       0
dtype: int64

#### **2.2.4. tree_rings Datasets**

In [15]:
df_tree_rings.head(50)

      year  n_tree  europe_temp_index
0   2000.0    1.10               0.85
1   1999.0    0.39               0.79
2   1998.0    1.13               0.72
3   1997.0    0.97               0.87
4   1996.0    1.07               0.19
5   1995.0    0.60               0.49
6   1994.0    1.84               1.32
7   1993.0    0.53               0.32
8   1992.0    0.36               0.54
9   1991.0    0.79               0.69
10  1990.0    0.87               0.55
11  1989.0    1.06               0.43
12  1988.0    1.08               0.50
13  1987.0   -0.36              -0.26
14  1986.0    1.10               0.42
15  1985.0    0.49               0.03
16  1984.0    0.44              -0.45
17  1983.0    0.61               0.47
18  1982.0    0.63               0.31
19  1981.0   -0.06              -0.19
20  1980.0    0.87               0.02
21  1979.0    0.49              -0.10
22  1978.0    0.55              -0.54
23  1977.0    0.32              -0.52
24  1976.0    0.21               0.09
25  1975.0   -1.11              -0.39
26  1974.0    0.02              -0.18
27  1973.0   -0.08               0.10
28  1972.0    0.30              -0.01
29  1971.0    0.24               0.05
30  1970.0    0.64               0.47
31  1969.0    1.33               0.37
32  1968.0   -0.47              -0.24
33  1967.0    0.01               0.12
34  1966.0   -0.62              -0.24
35  1965.0   -0.29              -0.80
36  1964.0    0.20              -0.02
37  1963.0    0.03              -0.18
38  1962.0   -0.55              -0.33
39  1961.0   -0.21              -0.11
40  1960.0   -0.03               0.29
41  1959.0    0.05               0.69
42  1958.0   -0.23               0.15
43  1957.0   -0.17              -0.09
44  1956.0    0.13              -0.35
45  1955.0    0.54               0.17
46  1954.0    0.17               0.07
47  1953.0    0.78               0.62
48  1952.0    0.13               0.64
49  1951.0    0.39               0.53

In [16]:
df_tree_rings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2252 entries, 0 to 2251
Data columns (total 3 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   year               2000 non-null   float64
 1   n_tree             2000 non-null   float64
 2   europe_temp_index  2000 non-null   float64
dtypes: float64(3)
memory usage: 52.9 KB

#### **2.2.5. Volcano Datasets**

In [17]:
df_volcano.head(50)

,volcano_number,volcano_name,primary_volcano_type,last_eruption_year,country,region,subregion,latitude,longitude,elevation,...,major_rock_5,minor_rock_1,minor_rock_2,minor_rock_3,minor_rock_4,minor_rock_5,population_within_5_km,population_within_10_km,population_within_30_km,population_within_100_km
0,283001,Abu,Shield(s),-6850,Japan,"Japan, Taiwan, Marianas",Honshu,34.500,131.600,641,...,,,,,,,3597,9594,117805,4071152
1,355096,Acamarachi,Stratovolcano,Unknown,Chile,South America,"Northern Chile, Bolivia and Argentina",-23.292,-67.618,6023,...,,,,,,,0,7,294,9092
2,342080,Acatenango,Stratovolcano(es),1972,Guatemala,México and Central America,Guatemala,14.501,-90.876,3976,...,,Basalt / Picro-Basalt,,,,,4329,60730,1042836,7634778
3,213004,Acigol-Nevsehir,Caldera,-2080,Turkey,Mediterranean and Western Asia,Turkey,38.537,34.621,1683,...,,,,,,,127863,127863,218469,2253483
4,321040,Adams,Stratovolcano,950,United States,Canada and Western USA,USA (Washington),46.206,-121.490,3742,...,,Dacite,,,,,0,70,4019,393303
5,283170,Adatarayama,Stratovolcano(es),1996,Japan,"Japan, Taiwan, Marianas",Honshu,37.647,140.281,1728,...,,Dacite,Basalt / Picro-Basalt,,,,428,3936,717078,5024654
6,221170,Adwa,Stratovolcano,Unknown,Ethiopia,Africa and Red Sea,Africa (northeastern) and Red Sea,10.070,40.840,1733,...,,,,,,,101,485,18645,1242922
7,221110,Afdera,Stratovolcano,Unknown,Ethiopia,Africa and Red Sea,Africa (northeastern) and Red Sea,13.088,40.853,1250,...,,Basalt / Picro-Basalt,Trachybasalt / Tephrite Basanite,Andesite / Basaltic Andesite,,,51,6042,8611,161009
8,284160,Agrigan,Stratovolcano,1917,United States,"Japan, Taiwan, Marianas","Izu, Volcano, and Mariana Islands",18.770,145.670,965,...,,,,,,,0,0,0,0
9,342100,Agua,Stratovolcano,Unknown,Guatemala,México and Central America,Guatemala,14.465,-90.743,3760,...,,Dacite,,,,,9890,114404,2530449,7441660
10,382090,Agua de Pau,Stratovolcano,1564,Portugal,Atlantic Ocean,Azores,37.770,-25.470,947,...,,,,,,,406,17272,113131,119653
11,358062,Aguilera,Stratovolcano,-1250,Chile,South America,Southern Chile and Argentina,-50.330,-73.750,2546,...,,,,,,,0,0,103,5698
12,264020,Agung,Stratovolcano,2019,Indonesia,Indonesia,Lesser Sunda Islands,-8.343,115.508,2997,...,,,,,,,5657,76781,968381,4550176
13,284141,Ahyi,Submarine,2014,United States,"Japan, Taiwan, Marianas","Izu, Volcano, and Mariana Islands",20.420,145.030,-75,...,,,,,,,0,0,0,0
14,282080,Aira,Caldera,2020,Japan,"Japan, Taiwan, Marianas",Ryukyu Islands and Kyushu,31.593,130.657,1117,...,,,,,,,4918,113874,905254,2610033
15,300125,Akademia Nauk,Stratovolcano(es),1996,Russia,Kamchatka and Mainland Asia,Kamchatka Peninsula,53.980,159.450,1180,...,,Basalt / Picro-Basalt,Rhyolite,,,,3,3,615,12484
16,283130,Akagisan,Stratovolcano,Unknown,Japan,"Japan, Taiwan, Marianas",Honshu,36.560,139.193,1828,...,,Dacite,,,,,961,4538,1116366,16718375
17,285070,Akan,Caldera,2008,Japan,"Japan, Taiwan, Marianas",Hokkaido,43.384,144.013,1499,...,,,,,,,2062,2062,9756,929538
18,283230,Akita-Komagatake,Stratovolcano(es),1971,Japan,"Japan, Taiwan, Marianas",Honshu,39.761,140.799,1637,...,,,,,,,376,3864,216708,2521611
19,283260,Akita-Yakeyama,Stratovolcano,1997,Japan,"Japan, Taiwan, Marianas",Honshu,39.964,140.757,1366,...,,Dacite,,,,,127,721,55493,3122037
20,282022,Akusekijima,Stratovolcano(es),Unknown,Japan,"Japan, Taiwan, Marianas",Ryukyu Islands and Kyushu,29.465,129.594,555,...,,,,,,,52,52,199,749
21,311320,Akutan,Stratovolcano,1992,United States,Alaska,Aleutian Islands,54.134,-165.986,1303,...,,Trachyte / Trachydacite,Dacite,,,,0,24,233,4361
22,290390,Alaid,Stratovolcano,2018,Russia,Kuril Islands,Kuril Islands,50.861,155.565,2285,...,,,,,,,0,64,64,2887
23,221112,Alayta,Shield,1915,Ethiopia,Africa and Red Sea,Africa (northeastern) and Red Sea,12.888,40.573,1496,...,,,,,,,156,925,13459,330411
24,353040,Alcedo,Shield,1993,Ecuador,South America,Galapagos Islands,-0.430,-91.120,1130,...,,Rhyolite,Dacite,Andesite / Basaltic Andesite,,,290,290,388,10756
25,221090,Ale Bagu,Stratovolcano,Unknown,Ethiopia,Africa and Red Sea,Africa (northeastern) and Red Sea,13.512,40.631,988,...,,,,,,,2,919,8424,278270
26,221040,Alid,Stratovolcano,Unknown,Eritrea,Africa and Red Sea,Africa (northeastern) and Red Sea,14.880,39.920,904,...,Trachyte / Trachydacite,,,,,,517,2447,25942,1216179
27,352031,Aliso,Stratovolcano,-2450,Ecuador,South America,Ecuador,-0.530,-78.000,4267,...,,,,,,,0,0,0,0
28,320020,Alligator Lake,Volcanic field,Unknown,Canada,Canada and Western USA,Canada,60.420,-135.420,2217,...,,,,,,,0,0,47,20636
29,342040,Almolonga,Stratovolcano,1818,Guatemala,México and Central America,Guatemala,14.797,-91.519,3173,...,,Basalt / Picro-Basalt,,,,,91323,287487,1126942,6828403
30,300450,Alney-Chashakondzha,Stratovolcano,1600,Russia,Kamchatka and Mainland Asia,Kamchatka Peninsula,56.656,159.647,2570,...,,Rhyolite,Dacite,,,,0,0,3,10679
31,221060,Alu-Dalafilla,Fissure vent(s),2008,Ethiopia,Africa and Red Sea,Africa (northeastern) and Red Sea,13.793,40.553,578,...,,,,,,,0,9,11209,478054
32,221270,Alutu,Stratovolcano,-50,Ethiopia,Africa and Red Sea,Africa (northeastern) and Red Sea,7.770,38.780,2335,...,,,,,,,6011,25619,314216,6813710
33,311390,Amak,Stratovolcano,1796,United States,Alaska,Aleutian Islands,55.424,-163.149,488,...,,,,,,,0,0,0,1345
34,268072,Amasing,Stratovolcano(es),Unknown,Indonesia,Indonesia,Halmahera,-0.530,127.480,1030,...,,,,,,,59,803,26015,92417
35,257030,Ambae,Shield,2018,Vanuatu,Melanesia and Australia,Vanuatu,-15.389,167.835,1496,...,,,,,,,73,1279,4326,73308
36,273088,Ambalatungan Group,Compound,Unknown,Philippines,Philippines and SE Asia,Luzon,17.320,121.100,2329,...,,,,,,,493,3803,55724,4652400
37,266020,Ambang,Complex,2005,Indonesia,Indonesia,Sulawesi,0.750,124.420,1795,...,,,,,,,9155,46469,319137,1730602
38,254020,Ambitle,Stratovolcano,-350,Papua New Guinea,Melanesia and Australia,New Ireland,-4.080,153.650,450,...,Trachyte / Trachydacite,,,,,,1643,9195,9779,24367
39,233011,Ambre-Bobaomby,Volcanic field,Unknown,Madagascar,Middle East and Indian Ocean,Indian Ocean (western),-12.600,49.150,1475,...,Foidite,,,,,,20396,20396,51426,408436
40,257040,Ambrym,Pyroclastic shield,2018,Vanuatu,Melanesia and Australia,Vanuatu,-16.250,168.120,1334,...,,,,,,,9,186,10826,63999
41,234001,Amsterdam Island,Stratovolcano,Unknown,France,Middle East and Indian Ocean,Indian Ocean (southern),-37.830,77.520,881,...,,,,,,,0,0,0,0
42,311190,Amukta,Stratovolcano,1997,United States,Alaska,Aleutian Islands,52.500,-171.252,1066,...,,,,,,,0,0,0,0
43,284200,Anatahan,Stratovolcano,2008,United States,"Japan, Taiwan, Marianas","Izu, Volcano, and Mariana Islands",16.350,145.670,790,...,,,,,,,0,0,0,0
44,300390,Anaun,Stratovolcano,Unknown,Russia,Kamchatka and Mainland Asia,Kamchatka Peninsula,56.320,158.830,1828,...,,,,,,,2,4,56,5933
45,354004,Andahua-Orcopampa,Pyroclastic cone(s),1490,Peru,South America,Peru,-15.420,-72.330,4713,...,,Trachyte / Trachydacite,,,,,10317,10317,16541,171897
46,390023,Andrus,Shield(s),Unknown,Antarctica,Antarctica,Antarctica and South Sandwich Islands,-75.800,-132.330,2978,...,,,,,,,0,0,0,0
47,257110,Aneityum,Stratovolcano(es),Unknown,Vanuatu,Melanesia and Australia,Vanuatu,-20.200,169.780,852,...,,,,,,,176,692,703,22731
48,312090,Aniakchak,Caldera,1931,United States,Alaska,Alaska Peninsula,56.880,-158.170,1341,...,,Basalt / Picro-Basalt,Trachyte / Trachydacite,Trachyandesite / Basaltic Trachyandesite,,,0,0,36,479
49,357153,Antillanca Volcanic Complex,Stratovolcano(es),-230,Chile,South America,Central Chile and Argentina,-40.783,-72.150,1979,...,,,,,,,87,521,5986,530586

In [18]:
df_volcano['region'].value_counts()

region
South America                     117
Japan, Taiwan, Marianas           102
Indonesia                          95
México and Central America         93
Africa and Red Sea                 79
Kamchatka and Mainland Asia        78
Canada and Western USA             60
Melanesia and Australia            45
Alaska                             38
Mediterranean and Western Asia     35
Philippines and SE Asia            33
New Zealand to Fiji                29
Iceland and Arctic Ocean           29
Middle East and Indian Ocean       27
Kuril Islands                      25
Antarctica                         25
Atlantic Ocean                     21
West Indies                        16
Hawaii and Pacific Ocean           11
Name: count, dtype: int64

In [19]:
df_volcano.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 958 entries, 0 to 957
Data columns (total 26 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   volcano_number            958 non-null    int64
 1   volcano_name              958 non-null    object
 2   primary_volcano_type      958 non-null    object
 3   last_eruption_year        958 non-null    object
 4   country                   958 non-null    object
 5   region                    958 non-null    object
 6   subregion                 958 non-null    object
 7   latitude                  958 non-null    float64
 8   longitude                 958 non-null    float64
 9   elevation                 958 non-null    int64
 10  tectonic_settings         958 non-null    object
 11  evidence_category         958 non-null    object
 12  major_rock_1              958 non-null    object
 13  major_rock_2              958 non-null    object
 14  major_rock_3              958 non-null    object
 15  major_rock_4              958 non-null    object
 16  major_rock_5              958 non-null    object
 17  minor_rock_1              958 non-null    object
 18  minor_rock_2              958 non-null    object
 19  minor_rock_3              958 non-null    object
 20  minor_rock_4              958 non-null    object
 21  minor_rock_5              958 non-null    object
 22  population_within_5_km    958 non-null    int64
 23  population_within_10_km   958 non-null    int64
 24  population_within_30_km   958 non-null    int64
 25  population_within_100_km  958 non-null    int64
dtypes: float64(2), int64(6), object(18)
memory usage: 194.7+ KB

In [20]:
df_volcano.isnull().sum()

volcano_number              0
volcano_name                0
primary_volcano_type        0
last_eruption_year          0
country                     0
region                      0
subregion                   0
latitude                    0
longitude                   0
elevation                   0
tectonic_settings           0
evidence_category           0
major_rock_1                0
major_rock_2                0
major_rock_3                0
major_rock_4                0
major_rock_5                0
minor_rock_1                0
minor_rock_2                0
minor_rock_3                0
minor_rock_4                0
minor_rock_5                0
population_within_5_km      0
population_within_10_km     0
population_within_30_km     0
population_within_100_km    0
dtype: int64

In [22]:
kolom_inti = [
    'volcano_number',
    'volcano_name',
    'region',
    'primary_volcano_type',
    'tectonic_settings',
    'elevation',
    'major_rock_1',
    'major_rock_2',
    'major_rock_3',
    'major_rock_4',
    'major_rock_5',
    'population_within_5_km',    # <-- Mulai masukin populasinya
    'population_within_10_km',
    'population_within_30_km',
    'population_within_100_km'
]

df_volcano_new = df_volcano[kolom_inti].copy()
df_volcano_new.head(50)

,volcano_number,volcano_name,region,primary_volcano_type,tectonic_settings,elevation,major_rock_1,major_rock_2,major_rock_3,major_rock_4,major_rock_5,population_within_5_km,population_within_10_km,population_within_30_km,population_within_100_km
0,283001,Abu,"Japan, Taiwan, Marianas",Shield(s),Subduction zone / Continental crust (>25 km),641,Andesite / Basaltic Andesite,Basalt / Picro-Basalt,Dacite,,,3597,9594,117805,4071152
1,355096,Acamarachi,South America,Stratovolcano,Subduction zone / Continental crust (>25 km),6023,Dacite,Andesite / Basaltic Andesite,,,,0,7,294,9092
2,342080,Acatenango,México and Central America,Stratovolcano(es),Subduction zone / Continental crust (>25 km),3976,Andesite / Basaltic Andesite,Dacite,,,,4329,60730,1042836,7634778
3,213004,Acigol-Nevsehir,Mediterranean and Western Asia,Caldera,Intraplate / Continental crust (>25 km),1683,Rhyolite,Dacite,Basalt / Picro-Basalt,Andesite / Basaltic Andesite,,127863,127863,218469,2253483
4,321040,Adams,Canada and Western USA,Stratovolcano,Subduction zone / Continental crust (>25 km),3742,Andesite / Basaltic Andesite,Basalt / Picro-Basalt,,,,0,70,4019,393303
5,283170,Adatarayama,"Japan, Taiwan, Marianas",Stratovolcano(es),Subduction zone / Continental crust (>25 km),1728,Andesite / Basaltic Andesite,,,,,428,3936,717078,5024654
6,221170,Adwa,Africa and Red Sea,Stratovolcano,Rift zone / Intermediate crust (15-25 km),1733,Rhyolite,Basalt / Picro-Basalt,Trachyte / Trachydacite,,,101,485,18645,1242922
7,221110,Afdera,Africa and Red Sea,Stratovolcano,Rift zone / Intermediate crust (15-25 km),1250,Rhyolite,,,,,51,6042,8611,161009
8,284160,Agrigan,"Japan, Taiwan, Marianas",Stratovolcano,Subduction zone / Crustal thickness unknown,965,Basalt / Picro-Basalt,Andesite / Basaltic Andesite,,,,0,0,0,0
9,342100,Agua,México and Central America,Stratovolcano,Subduction zone / Continental crust (>25 km),3760,Andesite / Basaltic Andesite,,,,,9890,114404,2530449,7441660
10,382090,Agua de Pau,Atlantic Ocean,Stratovolcano,Rift zone / Oceanic crust (< 15 km),947,Trachyte / Trachydacite,Trachybasalt / Tephrite Basanite,Basalt / Picro-Basalt,Trachyandesite / Basaltic Trachyandesite,,406,17272,113131,119653
11,358062,Aguilera,South America,Stratovolcano,Subduction zone / Continental crust (>25 km),2546,Dacite,,,,,0,0,103,5698
12,264020,Agung,Indonesia,Stratovolcano,Subduction zone / Continental crust (>25 km),2997,Andesite / Basaltic Andesite,,,,,5657,76781,968381,4550176
13,284141,Ahyi,"Japan, Taiwan, Marianas",Submarine,Subduction zone / Crustal thickness unknown,-75,Andesite / Basaltic Andesite,Basalt / Picro-Basalt,,,,0,0,0,0
14,282080,Aira,"Japan, Taiwan, Marianas",Caldera,Subduction zone / Continental crust (>25 km),1117,Andesite / Basaltic Andesite,Dacite,Rhyolite,,,4918,113874,905254,2610033
15,300125,Akademia Nauk,Kamchatka and Mainland Asia,Stratovolcano(es),Subduction zone / Continental crust (>25 km),1180,Andesite / Basaltic Andesite,Dacite,,,,3,3,615,12484
16,283130,Akagisan,"Japan, Taiwan, Marianas",Stratovolcano,Subduction zone / Continental crust (>25 km),1828,Andesite / Basaltic Andesite,,,,,961,4538,1116366,16718375
17,285070,Akan,"Japan, Taiwan, Marianas",Caldera,Subduction zone / Continental crust (>25 km),1499,Andesite / Basaltic Andesite,Dacite,Basalt / Picro-Basalt,Rhyolite,,2062,2062,9756,929538
18,283230,Akita-Komagatake,"Japan, Taiwan, Marianas",Stratovolcano(es),Subduction zone / Continental crust (>25 km),1637,Basalt / Picro-Basalt,Andesite / Basaltic Andesite,,,,376,3864,216708,2521611
19,283260,Akita-Yakeyama,"Japan, Taiwan, Marianas",Stratovolcano,Subduction zone / Continental crust (>25 km),1366,Andesite / Basaltic Andesite,,,,,127,721,55493,3122037
20,282022,Akusekijima,"Japan, Taiwan, Marianas",Stratovolcano(es),Subduction zone / Oceanic crust (< 15 km),555,Andesite / Basaltic Andesite,Dacite,,,,52,52,199,749
21,311320,Akutan,Alaska,Stratovolcano,Subduction zone / Intermediate crust (15-25 km),1303,Basalt / Picro-Basalt,Andesite / Basaltic Andesite,Trachyandesite / Basaltic Trachyandesite,,,0,24,233,4361
22,290390,Alaid,Kuril Islands,Stratovolcano,Subduction zone / Continental crust (>25 km),2285,Basalt / Picro-Basalt,Andesite / Basaltic Andesite,,,,0,64,64,2887
23,221112,Alayta,Africa and Red Sea,Shield,Rift zone / Intermediate crust (15-25 km),1496,Basalt / Picro-Basalt,Trachyte / Trachydacite,Trachyandesite / Basaltic Trachyandesite,,,156,925,13459,330411
24,353040,Alcedo,South America,Shield,Rift zone / Oceanic crust (< 15 km),1130,Basalt / Picro-Basalt,,,,,290,290,388,10756
25,221090,Ale Bagu,Africa and Red Sea,Stratovolcano,Rift zone / Intermediate crust (15-25 km),988,Basalt / Picro-Basalt,Trachyte / Trachydacite,Rhyolite,,,2,919,8424,278270
26,221040,Alid,Africa and Red Sea,Stratovolcano,Rift zone / Intermediate crust (15-25 km),904,Rhyolite,Basalt / Picro-Basalt,Andesite / Basaltic Andesite,Trachyandesite / Basaltic Trachyandesite,Trachyte / Trachydacite,517,2447,25942,1216179
27,352031,Aliso,South America,Stratovolcano,Subduction zone / Continental crust (>25 km),4267,Andesite / Basaltic Andesite,Rhyolite,Dacite,,,0,0,0,0
28,320020,Alligator Lake,Canada and Western USA,Volcanic field,Intraplate / Continental crust (>25 km),2217,Basalt / Picro-Basalt,Trachybasalt / Tephrite Basanite,,,,0,0,47,20636
29,342040,Almolonga,México and Central America,Stratovolcano,Subduction zone / Continental crust (>25 km),3173,Dacite,Andesite / Basaltic Andesite,,,,91323,287487,1126942,6828403
30,300450,Alney-Chashakondzha,Kamchatka and Mainland Asia,Stratovolcano,Subduction zone / Continental crust (>25 km),2570,Basalt / Picro-Basalt,Andesite / Basaltic Andesite,,,,0,0,3,10679
31,221060,Alu-Dalafilla,Africa and Red Sea,Fissure vent(s),Rift zone / Intermediate crust (15-25 km),578,Basalt / Picro-Basalt,Andesite / Basaltic Andesite,Trachyte / Trachydacite,Rhyolite,,0,9,11209,478054
32,221270,Alutu,Africa and Red Sea,Stratovolcano,Rift zone / Continental crust (>25 km),2335,Rhyolite,Dacite,Basalt / Picro-Basalt,,,6011,25619,314216,6813710
33,311390,Amak,Alaska,Stratovolcano,Subduction zone / Continental crust (>25 km),488,Andesite / Basaltic Andesite,,,,,0,0,0,1345
34,268072,Amasing,Indonesia,Stratovolcano(es),Subduction zone / Oceanic crust (< 15 km),1030,Andesite / Basaltic Andesite,,,,,59,803,26015,92417
35,257030,Ambae,Melanesia and Australia,Shield,Subduction zone / Intermediate crust (15-25 km),1496,Basalt / Picro-Basalt,,,,,73,1279,4326,73308
36,273088,Ambalatungan Group,Philippines and SE Asia,Compound,Subduction zone / Continental crust (>25 km),2329,Dacite,Andesite / Basaltic Andesite,,,,493,3803,55724,4652400
37,266020,Ambang,Indonesia,Complex,Subduction zone / Continental crust (>25 km),1795,Andesite / Basaltic Andesite,,,,,9155,46469,319137,1730602
38,254020,Ambitle,Melanesia and Australia,Stratovolcano,Subduction zone / Crustal thickness unknown,450,Phono-tephrite / Tephri-phonolite,Trachybasalt / Tephrite Basanite,Trachyandesite / Basaltic Trachyandesite,Basalt / Picro-Basalt,Trachyte / Trachydacite,1643,9195,9779,24367
39,233011,Ambre-Bobaomby,Middle East and Indian Ocean,Volcanic field,Intraplate / Continental crust (>25 km),1475,Basalt / Picro-Basalt,Rhyolite,Trachyte / Trachydacite,Phonolite,Foidite,20396,20396,51426,408436
40,257040,Ambrym,Melanesia and Australia,Pyroclastic shield,Subduction zone / Intermediate crust (15-25 km),1334,Basalt / Picro-Basalt,Andesite / Basaltic Andesite,Dacite,,,9,186,10826,63999
41,234001,Amsterdam Island,Middle East and Indian Ocean,Stratovolcano,Rift zone / Oceanic crust (< 15 km),881,Basalt / Picro-Basalt,,,,,0,0,0,0
42,311190,Amukta,Alaska,Stratovolcano,Subduction zone / Intermediate crust (15-25 km),1066,Andesite / Basaltic Andesite,,,,,0,0,0,0
43,284200,Anatahan,"Japan, Taiwan, Marianas",Stratovolcano,Subduction zone / Crustal thickness unknown,790,Andesite / Basaltic Andesite,Dacite,Basalt / Picro-Basalt,Trachyandesite / Basaltic Trachyandesite,,0,0,0,0
44,300390,Anaun,Kamchatka and Mainland Asia,Stratovolcano,Subduction zone / Continental crust (>25 km),1828,Basalt / Picro-Basalt,Andesite / Basaltic Andesite,,,,2,4,56,5933
45,354004,Andahua-Orcopampa,South America,Pyroclastic cone(s),Subduction zone / Continental crust (>25 km),4713,Trachyandesite / Basaltic Trachyandesite,,,,,10317,10317,16541,171897
46,390023,Andrus,Antarctica,Shield(s),Intraplate / Continental crust (>25 km),2978,Trachyte / Trachydacite,Rhyolite,Trachyandesite / Basaltic Trachyandesite,,,0,0,0,0
47,257110,Aneityum,Melanesia and Australia,Stratovolcano(es),Subduction zone / Intermediate crust (15-25 km),852,Basalt / Picro-Basalt,Andesite / Basaltic Andesite,,,,176,692,703,22731
48,312090,Aniakchak,Alaska,Caldera,Subduction zone / Continental crust (>25 km),1341,Andesite / Basaltic Andesite,Dacite,,,,0,0,36,479
49,357153,Antillanca Volcanic Complex,South America,Stratovolcano(es),Subduction zone / Continental crust (>25 km),1979,Basalt / Picro-Basalt,Andesite / Basaltic Andesite,,,,87,521,5986,530586

In [23]:
df_eruption_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11178 entries, 0 to 11177
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   volcano_number     11178 non-null  int64
 1   volcano_name       11178 non-null  object
 2   eruption_number    11178 non-null  int64
 3   eruption_category  11178 non-null  object
 4   vei                8272 non-null   float64
 5   start_year         11177 non-null  float64
dtypes: float64(2), int64(2), object(2)
memory usage: 524.1+ KB

In [24]:
df_event_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41322 entries, 0 to 41321
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   volcano_number       41322 non-null  int64
 1   volcano_name         41322 non-null  object
 2   eruption_number      41322 non-null  int64
 3   eruption_start_year  41322 non-null  int64
 4   event_number         41322 non-null  int64
 5   event_type           41322 non-null  object
dtypes: int64(4), object(2)
memory usage: 1.9+ MB

In [25]:
df_volcano_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 958 entries, 0 to 957
Data columns (total 15 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   volcano_number            958 non-null    int64
 1   volcano_name              958 non-null    object
 2   region                    958 non-null    object
 3   primary_volcano_type      958 non-null    object
 4   tectonic_settings         958 non-null    object
 5   elevation                 958 non-null    int64
 6   major_rock_1              958 non-null    object
 7   major_rock_2              958 non-null    object
 8   major_rock_3              958 non-null    object
 9   major_rock_4              958 non-null    object
 10  major_rock_5              958 non-null    object
 11  population_within_5_km    958 non-null    int64
 12  population_within_10_km   958 non-null    int64
 13  population_within_30_km   958 non-null    int64
 14  population_within_100_km  958 non-null    int64
dtypes: int64(6), object(9)
memory usage: 112.4+ KB

In [26]:
df_volcano_new.head()

,volcano_number,volcano_name,region,primary_volcano_type,tectonic_settings,elevation,major_rock_1,major_rock_2,major_rock_3,major_rock_4,major_rock_5,population_within_5_km,population_within_10_km,population_within_30_km,population_within_100_km
0,283001,Abu,"Japan, Taiwan, Marianas",Shield(s),Subduction zone / Continental crust (>25 km),641,Andesite / Basaltic Andesite,Basalt / Picro-Basalt,Dacite,,,3597,9594,117805,4071152
1,355096,Acamarachi,South America,Stratovolcano,Subduction zone / Continental crust (>25 km),6023,Dacite,Andesite / Basaltic Andesite,,,,0,7,294,9092
2,342080,Acatenango,México and Central America,Stratovolcano(es),Subduction zone / Continental crust (>25 km),3976,Andesite / Basaltic Andesite,Dacite,,,,4329,60730,1042836,7634778
3,213004,Acigol-Nevsehir,Mediterranean and Western Asia,Caldera,Intraplate / Continental crust (>25 km),1683,Rhyolite,Dacite,Basalt / Picro-Basalt,Andesite / Basaltic Andesite,,127863,127863,218469,2253483
4,321040,Adams,Canada and Western USA,Stratovolcano,Subduction zone / Continental crust (>25 km),3742,Andesite / Basaltic Andesite,Basalt / Picro-Basalt,,,,0,70,4019,393303

In [28]:
df_eruption_new.head()

,volcano_number,volcano_name,eruption_number,eruption_category,vei,start_year
0,266030,Soputan,22354,Confirmed Eruption,NaN,2020.0
1,343100,San Miguel,22355,Confirmed Eruption,NaN,2020.0
2,233020,"Fournaise, Piton de la",22343,Confirmed Eruption,NaN,2020.0
3,345020,Rincon de la Vieja,22346,Confirmed Eruption,NaN,2020.0
4,353010,Fernandina,22347,Confirmed Eruption,NaN,2020.0

In [30]:
df_eruption_new.head()

,volcano_number,volcano_name,eruption_number,eruption_category,vei,start_year
0,266030,Soputan,22354,Confirmed Eruption,NaN,2020.0
1,343100,San Miguel,22355,Confirmed Eruption,NaN,2020.0
2,233020,"Fournaise, Piton de la",22343,Confirmed Eruption,NaN,2020.0
3,345020,Rincon de la Vieja,22346,Confirmed Eruption,NaN,2020.0
4,353010,Fernandina,22347,Confirmed Eruption,NaN,2020.0